name: Snyk Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-app-image .

    - name: Install Snyk CLI
      run: |
        npm install -g snyk
        snyk --version

    - name: Run Snyk container scan
      run: |
        snyk container test my-app-image --file=Dockerfile \
          --sarif-file-output=snyk.sarif \
          --severity-threshold=medium
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
